Dz master update
js-tasks-ru/htmlcss-20230411_igorvs pull request #16
Opened 2023-05-10 09:23 UTC by IgVSIII

2023-05-10 09:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-11 14:44 UTC, GSemikozov requested changes

2023-05-11 14:44 UTC, GSemikozov commented on components/page/page.css
> +        grid-template-areas: "Header"
футер скрывать не надо

2023-05-11 14:44 UTC, GSemikozov commented on components/page/page.css
> +@media screen and (max-width: 375px) {
моб версию лучше делать хотя бы на 767 )

2023-05-11 15:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-11 15:01 UTC, GSemikozov approved these changes

2023-05-11 15:01 UTC, merged