Dz3 button
js-tasks-ru/htmlcss-20230411_igorvs pull request #7
Opened 2023-04-20 15:47 UTC by IgVSIII

2023-04-20 15:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-20 15:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-20 19:41 UTC, GSemikozov requested changes

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');
см коммент по предыдущему ПР-у

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 15px 66px;
высота точно соответствует макету?

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: 0px;
не хватает стилей для описания текста

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.wrapper {
это не элемент блока .button, к данному блоку не имеет отношения, так что - удалим

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-color_primary {
блок - .button, поэтому модификатор - .button_primary

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-color_primary_hover {
для ховера используем встроенный псевдо-класс - .button_primary:hover

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button-color_primary_disabled {
для всех кнопок - одно состояние, `.button:disabled`

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    background-color: var(--primary-disabled);
pointer-events: none

2023-04-20 19:41 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__text {
лишний элемент, стили надо перенести в класс блока

2023-04-21 06:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-21 06:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-21 15:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-21 20:12 UTC, GSemikozov requested changes

2023-04-21 20:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
просто height (не нужно чтобы кнопка росла в высоту)

2023-04-21 20:12 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: var(--white);
не хватает `padding: 15px 15px 14px`

2023-04-22 05:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-22 05:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-24 19:22 UTC, GSemikozov approved these changes

2023-04-24 19:22 UTC, merged