add solution for 4-module histogram
js-tasks-ru/htmlcss-20230411_igorvs pull request #8
Opened 2023-04-26 17:17 UTC by IgVSIII

2023-04-26 17:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-28 14:33 UTC, GSemikozov requested changes

2023-04-28 14:33 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2023-04-28 14:33 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 6px;
здесь все-таки марджины

2023-04-28 14:33 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: flex-end;
здесь не хватает фиксированной высоты как в макете, чтобы колонкам задавать высоту относительно этого значения в процентах

2023-04-28 14:33 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
flex-basis

2023-04-28 14:33 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 50px;
высоту - в процентах

2023-04-28 14:33 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__graphic-element-hight {
.histogram__graphic-element_full

2023-04-28 17:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-28 17:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 14:58 UTC, GSemikozov approved these changes

2023-05-01 14:59 UTC, merged